### ISSUE TITLE
[Sonic 2] I got a Game Over despite having 18 Lives as Tails

### ISSUE THREAD

**Issue by ViperAcidZX** [JackoboLeChocobo/Sonic-1-2-Decomp-Build#3]
I was playing this fork of the Decompilation and while playing as Tails, I fell into this trap in Aquatic Ruins Zone and died, but instead of spawning me back to the checkpoint/start of the level, it gave me a Game Over instead even though I had 18 lives prior to losing this one.

![S2-GameOverBug](https://user-images.githubusercontent.com/19318128/110258492-d87bf880-7f70-11eb-96c7-47ead3d1952a.png)

I was using an executable I compiled from the instructions from the Menu System mod from GameBanana.

**Comment by JackoboLeChocobo** [comment]
Fixed by ElspethThePict on scripts
